language: swift
os: osx
osx_image: xcode8
sudo: false

script:
  - xctool -project LocalNotificationScheduler/LocalNotificationScheduler.xcodeproj -scheme LocalNotificationScheduler -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project LocalNotificationScheduler/LocalNotificationScheduler.xcodeproj -scheme LocalNotificationSchedulerTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  
